kind = "web"
previewPath = "/"
title = "Full Stack School"
version = "0.0.1"

[[services]]
localPort = 3000
name = "web"
paths = ["/"]

[services.env]
PORT = "3000"

[services.development]
run = "pnpm --filter @workspace/school-app run dev"

[services.production]

[services.production.build]
args = ["pnpm", "--filter", "@workspace/school-app", "run", "build"]

[services.production.build.env]
NODE_ENV = "production"

[services.production.run]
args = ["pnpm", "--filter", "@workspace/school-app", "run", "start"]

[services.production.run.env]
PORT = "3000"
NODE_ENV = "production"
